### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by ivanjaros** [ninibe/netlog#10]
Hi, I just saw the Golang UK video https://www.youtube.com/watch?v=ysjcEN548yc
so I wanted to check out the project but it looks like it has been abandoned. Or is it rather considered completed?

The author has no new commits, and ninibe web shows nginx welcome screen. Seems like after that conference all work stopped.

**Comment by bictorman** [comment]
Hi,

The project's development is "on hold" until my life circumstances allow me to allocate time to it again. Things are far from done, actually until [this problem](https://github.com/ninibe/netlog/pull/6#discussion_r78627116) is solved, which [this improvement](https://github.com/ninibe/netlog/issues/7) was supposed to tackle, it's not really usable.

I'm not in a position to say with I'll pick up the project again, not in the short/mid term. But if there are any contributions, I'll find myself to fine some time to review them.

**Comment by ivanjaros** [comment]
OK, thanks for the info. I've noticed that this project depends on gommap which is dead for 5 years now and does not work on windows at all so I have to keep looking for something else anyway.
