### ISSUE TITLE
Join forces with Jocko

### ISSUE THREAD

**Issue by ivanjaros** [ninibe/netlog#12]
It seems like this project tries to be very Kafka-like. The Jocko(https://github.com/travisjeffery/jocko) project does the same. Maybe joining forces could be beneficial instead of two separate projects?

**Comment by bictorman** [comment]
Hi @ivanjaros please see #10 TL;DR: contributions are welcome.

**Comment by bictorman** [comment]
as I understand it Jocko aims to implement the kafka protocol. while netlog has ease of use as one of their main goals, so it can be used simply with curl. While the projects certainly share a lot of use cases I'd argue that they have different scopes.
