### ISSUE TITLE
segment headers

### ISSUE THREAD

**Issue by fgrosse** [ninibe/netlog#7]
As a follow up on https://github.com/ninibe/netlog/pull/6#discussion_r78650961 I'd like to propose a segment header for index files. The segment header should have the following properties:
- **store metadata**: for starters we want to put the segment creation timestamp
- **non-intrusive**: the existing code should basically continue to work like before
- **easy to upgrade**: its possible that we want to put more data into the segment header or maybe even change the index files format at some point. The header can support this by marking the schema of a segment

I am proposing the following format:

```
+----------------------------------------+
| version [1 byte] | createdTS [4 bytes] |
+----------------------------------------+
| first segment entry [ 16 bytes]        |
+----------------------------------------+
| second segment entry [ 16 bytes]       |
+----------------------------------------+
|  ...                                   |
+----------------------------------------+
```

Having a single byte for the version should be fine. That should at least be enough for the first 127 schema versions. If we ever exceed this we could think about using the highest bit of the version byte to indicate that another version byte is following. I doubt this will ever be the case but it is important for this reason that the version is the first field of the header.

Prepending a header before the actual index data is always non intrusive because it is only read once when a segment is opened and operation continues normally at the next byte offset after the header (`segment.NiFO` initially points to the next byte after the header).

I couldn't come up with more header fields for now so with this setup the header will be 5 bytes long. I kind of want to add three bytes up to the next power of two but there isn't really a good reason for this here so I left it as is. The version field enables us to add as much information as we want over time.

**Comment by bictorman** [comment]
Running out of versions is rarely a problem, actually netlog provisions [only 4 bits](https://github.com/ninibe/netlog/blob/b063449900867399171143ae2b0f60f326288e17/message.go#L104) for message schemas. In the unlikely scenario that we run out of versions it's easy to workaround as you mention.

So you want to add the header to the index? I think that might be a bit disruptive, not haven't looked much closely yet we might need to adapt at least all the binary search functions. Also, in the future the existence of the index itself might be even [called into question](https://github.com/ninibe/netlog/pull/5#issuecomment-245740907).

I think the data file could be a safer bet. From the top of my head it would only require adapting the [data reader jump reset](https://github.com/ninibe/netlog/blob/b063449900867399171143ae2b0f60f326288e17/biglog/reader.go#L80), and the [index initialization](https://github.com/ninibe/netlog/blob/b063449900867399171143ae2b0f60f326288e17/biglog/segment.go#L570).

But I'll try to find time to take a deeper look and give a more informed opinion.

**Comment by bictorman** [comment]
Indeed just those 2 places would do for a data file header, plus adapting a couple of segment tests that read the file directly.  Adding it to the index means offsetting the index size in a few places, mostly in the binary search.

Both are doable but I think using the data segment is much more transparent since there's never "math" involved in accessing it.

As for the header length, I think we should make it 16 bytes.  Unlike with the message header, space here is very cheap, 16 bytes per segment is nothing. That way the header size can be a version-independent constant for the foreseeable future. 16 happens also to be the default width in xxd so the header looks nicer...  :)

**Comment by fgrosse** [comment]
Putting the segment header in the data file makes things simpler which is
always better. I guess I was just still a little bit too focused on the
index files when writing the proposal.

About the header size: aligning it such that it's easy to work with as
developer using standard tools is worth a few extra bytes so I'm easily
convinced there as well :)

However, I don't think having a constant header size is something the code
should rely on. Instead the header size should depend on the version.

Victor Ruiz <notifications@github.com> schrieb am Do., 15. Sep. 2016, 23:50:

**Comment by bictorman** [comment]
There is no downside if we are over-provisioning the header (until/if you hit the limit of course).

Having the length strictly version dependent is less resilient. Think about the following scenario:

We release a new version that adds a new field to the header and we bump the version number. In the same release we introduce a nasty bug. The user upgrades and hits the bug, now the upgrade can not be rolled-back without loosing all the data written to the new segments, because the old version doesn’t know what the new version’s header length is, and while the new field could have potentially been ignored, nothing works without the header length.

A compromise could be to add the length to the header itself in a somewhat
predictable way.

```
+------------------+----------------------------------------+
| version [1 byte] | length  [1 byte] | createdTS [4 bytes] |
+-----------------------------------------------------------+
```

One could make the same argument about message versions, but there bytes are expensive, so it’s another set of tradeoffs.

**Comment by fgrosse** [comment]
I understand your argument but to me it was important for this structure to
be upgradeable. Maybe we should find more user cases for a segment header
then just the timestamp of its creation.

 I was imagining more meta intonation about the stored data but having this
on a segment level doesn't feel quite right either...

In the end my overview of netlog is still very limited so you lead the way
with this :)

Victor Ruiz <notifications@github.com> schrieb am Fr., 16. Sep. 2016, 13:54:

**Comment by bictorman** [comment]
Sure, the upgradeability is what the version number is for, linking the length to the version is only necessary when (if ever) there are 2 possible lengths. Actually after a bit more thought I think storing the length within the data would make maintaining compatibility (backwards and forward) much simpler.

This is segment data, it needs to be created and discarded with each segment, the alternative would be adding a new metadata file, but I don't think more files is something we should aim at unless it's really necessary.

It's hard trying to guess future use cases. Maybe one day segments could be "closed" (like elasticsearch indexes) without getting deleted. Maybe one day segments could get [compacted](https://cwiki.apache.org/confluence/display/KAFKA/Log+Compaction). Features like those could store data in the header. But today the only thing we need is the creation time.

**Comment by fgrosse** [comment]
Sorry for the long absence. After giving it some thought, I like your proposal of directly encoding the length in the header. It gives us good upgradeability and should generally be quite robust (at most the header information is lost in case of a bug as long as it can be parsed up to the complete length part).

A single byte for the header length should be enough for now. If and when we ever exceed a header length of 127 bytes we could implement the length using the same way [BER][1] encodes its length octets (definite long form). I already have some experience with BER encoding from https://github.com/fgrosse/PHPASN1.

So in summary I would implement the following format for now:
```
+------------------+----------------------------------------+
| version [1 byte] | length  [1 byte] | createdTS [4 bytes] |
+-----------------------------------------------------------+
```

these are my assumptions:
- the length contains the number of bytes that follow after the length part
- for version `0x01` this will be four bytes for the creation timestamp
- the header will be created upon segment creation and is not supposed to be changed afterwards (may change in future versions)
- each segment has its own independent header and no information is necessarily shared between headers (i.e. timestamps really refer to the timestamp of each individual segment file)

**It would be really cool if you could add the `Hacktoberfest` label to this issue so I can make this count in [the currently running Hacktoberfest by digitalocean and github][2].**

[1]: https://en.wikipedia.org/wiki/X.690#Length_octets
[2]: https://hacktoberfest.digitalocean.com/

**Comment by bictorman** [comment]
LGTM!
